### ISSUE TITLE
Unable to add device

### ISSUE THREAD

**Issue by JvAer** [jghaanstra/com.doorbird#12]
Unable to add device.

Hi,

I'm using Homey 2.1.2 and have CLI installed an older version of Doorbird 2.2.8. I have setup a new user with API permissions i the Doorbird app. When I want to add the device to Homey using it's IP and defined user I get the following error message.

![IMG_1989](https://user-images.githubusercontent.com/52112854/59968603-5a798300-953c-11e9-859a-9740dfda6578.jpg)

Is it an interoperabilty issue or have I missed something?

Joop

**Comment by jghaanstra** [comment]
I'm pretty sure you have missed something since there are no know issues with 2.2.8. So it's likely something on your end. Is the DoorBird on the same network as Homey, is there no firewall blocking the communication, are you sure the user has enough rights. Perhaps try giving it more rights to see if that works out.

I'm closing this as GitHub is not intended for support questions. Please use the forum for this, Github is used for feature requests and actual bugs.
